/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rongxianren_androidndktest_JNIHelper */

#ifndef _Included_com_rongxianren_androidndktest_JNIHelper
#define _Included_com_rongxianren_androidndktest_JNIHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rongxianren_androidndktest_JNIHelper
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rongxianren_androidndktest_JNIHelper_getStringFromC
  (JNIEnv *, jobject);


/*
 * Class:     com_rongxianren_androidndktest_JNIHelper
 * Method:    accessField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rongxianren_androidndktest_JNIHelper_accessField
  (JNIEnv *, jobject);



/*
 * Class:     com_rongxianren_androidndktest_JNIHelper
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_rongxianren_androidndktest_JNIHelper_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_rongxianren_androidndktest_JNIHelper
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rongxianren_androidndktest_JNIHelper_accessStaticField
  (JNIEnv *, jclass);

/*
 * Class:     com_rongxianren_androidndktest_JNIHelper
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_rongxianren_androidndktest_JNIHelper_accessStaticMethod
  (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
